// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OauthsColumns holds the columns for the "oauths" table.
	OauthsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "provider", Type: field.TypeString},
	}
	// OauthsTable holds the schema information for the "oauths" table.
	OauthsTable = &schema.Table{
		Name:       "oauths",
		Columns:    OauthsColumns,
		PrimaryKey: []*schema.Column{OauthsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "is_deleted", Type: field.TypeBool, Default: false},
		{Name: "username", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "nickname", Type: field.TypeString},
		{Name: "introduction", Type: field.TypeString, Default: ""},
		{Name: "avatar", Type: field.TypeString, Nullable: true},
		{Name: "create_at", Type: field.TypeTime},
		{Name: "last_login", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "password", Type: field.TypeString, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OauthsTable,
		UsersTable,
	}
)

func init() {
}
