// Code generated by ent, DO NOT EDIT.

package ent

import (
	"RTalky/ent/oauth"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Oauth is the model entity for the Oauth schema.
type Oauth struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider     string `json:"provider,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Oauth) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauth.FieldID:
			values[i] = new(sql.NullInt64)
		case oauth.FieldProvider:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Oauth fields.
func (o *Oauth) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauth.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			o.ID = int(value.Int64)
		case oauth.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				o.Provider = value.String
			}
		default:
			o.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Oauth.
// This includes values selected through modifiers, order, etc.
func (o *Oauth) Value(name string) (ent.Value, error) {
	return o.selectValues.Get(name)
}

// Update returns a builder for updating this Oauth.
// Note that you need to call Oauth.Unwrap() before calling this method if this Oauth
// was returned from a transaction, and the transaction was committed or rolled back.
func (o *Oauth) Update() *OauthUpdateOne {
	return NewOauthClient(o.config).UpdateOne(o)
}

// Unwrap unwraps the Oauth entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (o *Oauth) Unwrap() *Oauth {
	_tx, ok := o.config.driver.(*txDriver)
	if !ok {
		panic("ent: Oauth is not a transactional entity")
	}
	o.config.driver = _tx.drv
	return o
}

// String implements the fmt.Stringer.
func (o *Oauth) String() string {
	var builder strings.Builder
	builder.WriteString("Oauth(")
	builder.WriteString(fmt.Sprintf("id=%v, ", o.ID))
	builder.WriteString("provider=")
	builder.WriteString(o.Provider)
	builder.WriteByte(')')
	return builder.String()
}

// Oauths is a parsable slice of Oauth.
type Oauths []*Oauth
