// Code generated by ent, DO NOT EDIT.

package ent

import (
	"RTalky/ent/oauth"
	"RTalky/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OauthUpdate is the builder for updating Oauth entities.
type OauthUpdate struct {
	config
	hooks    []Hook
	mutation *OauthMutation
}

// Where appends a list predicates to the OauthUpdate builder.
func (ou *OauthUpdate) Where(ps ...predicate.Oauth) *OauthUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetProvider sets the "provider" field.
func (ou *OauthUpdate) SetProvider(s string) *OauthUpdate {
	ou.mutation.SetProvider(s)
	return ou
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (ou *OauthUpdate) SetNillableProvider(s *string) *OauthUpdate {
	if s != nil {
		ou.SetProvider(*s)
	}
	return ou
}

// Mutation returns the OauthMutation object of the builder.
func (ou *OauthUpdate) Mutation() *OauthMutation {
	return ou.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OauthUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OauthUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OauthUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OauthUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ou *OauthUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(oauth.Table, oauth.Columns, sqlgraph.NewFieldSpec(oauth.FieldID, field.TypeInt))
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.Provider(); ok {
		_spec.SetField(oauth.FieldProvider, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OauthUpdateOne is the builder for updating a single Oauth entity.
type OauthUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OauthMutation
}

// SetProvider sets the "provider" field.
func (ouo *OauthUpdateOne) SetProvider(s string) *OauthUpdateOne {
	ouo.mutation.SetProvider(s)
	return ouo
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (ouo *OauthUpdateOne) SetNillableProvider(s *string) *OauthUpdateOne {
	if s != nil {
		ouo.SetProvider(*s)
	}
	return ouo
}

// Mutation returns the OauthMutation object of the builder.
func (ouo *OauthUpdateOne) Mutation() *OauthMutation {
	return ouo.mutation
}

// Where appends a list predicates to the OauthUpdate builder.
func (ouo *OauthUpdateOne) Where(ps ...predicate.Oauth) *OauthUpdateOne {
	ouo.mutation.Where(ps...)
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OauthUpdateOne) Select(field string, fields ...string) *OauthUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated Oauth entity.
func (ouo *OauthUpdateOne) Save(ctx context.Context) (*Oauth, error) {
	return withHooks(ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OauthUpdateOne) SaveX(ctx context.Context) *Oauth {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OauthUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OauthUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (ouo *OauthUpdateOne) sqlSave(ctx context.Context) (_node *Oauth, err error) {
	_spec := sqlgraph.NewUpdateSpec(oauth.Table, oauth.Columns, sqlgraph.NewFieldSpec(oauth.FieldID, field.TypeInt))
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Oauth.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauth.FieldID)
		for _, f := range fields {
			if !oauth.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauth.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.Provider(); ok {
		_spec.SetField(oauth.FieldProvider, field.TypeString, value)
	}
	_node = &Oauth{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauth.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
