# deploy.yml
name: deploy RTalky backend to server
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 打印所有环境变量
      - name: Print all env
        run: |
          echo "dist/${{ secrets.ARCH }}/${{ secrets.DEPLOY_NAME }}"
          env

      # 切换分支并补全子模块
      - name: Checkout code (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # 使用 go:1.23.0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      # 编译
      - name: go build
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          swag init -g http/routes/router.go
          mkdir -p dist/${{ secrets.ARCH }}
          GOOS=${{ secrets.OS }} GOARCH=${{ secrets.ARCH }} go build -o dist/${{ secrets.ARCH }}/${{ secrets.DEPLOY_NAME }}_dev .
          ls -la dist/${{ secrets.ARCH }}

      # 部署
      - name: Deploy to Server
        uses: appleboy/scp-action@v1
        with:
          debug: true
          overwrite: true
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          strip_components: 2
          port: ${{ secrets.SSH_PORT }}
          source: "dist/${{ secrets.ARCH }}/${{ secrets.DEPLOY_NAME }}_dev"
          target: ${{ secrets.SSH_DEST_PATH }}

      # 重启服务
      - name: Restart service
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/service/rtalky
            ./rtalky_ctl.sh restart
            ./rtalky_ctl.sh status
